### ISSUE TITLE
又开新坑了🤣

### ISSUE THREAD

**Issue by jingyuexing** [peng-zhihui/OpenHeat#1]

**Comment by BackMountainDevil** [comment]
开源电烙铁很成熟了，推测一波加热神器（暖手宝），紫米那个发热的效果太局限

**Comment by hide-in-code** [comment]
> 开源电烙铁很成熟了，推测一波加热神器（暖手宝），紫米那个发热的效果太局限

我还说我好像在B站看见过类似的，没想起来是哪个up😂
