### ISSUE TITLE
不懂问一下，加热台上的电压只有5V么

### ISSUE THREAD

**Issue by wlllsama** [peng-zhihui/OpenHeat#13]
原理图上MOS电路那部分输入只有5V 那么BED_OUT有多少呢
24V输入了就被ME3116搞成5V了

**Comment by seishinkouki** [comment]
mos控制的是低端, 也就是负极, 加热台正极是直接接的供电24v

**Comment by wlllsama** [comment]
> mos控制的是低端, 也就是负极, 加热台正极是直接接的供电24v

看了展硕的原版图 看明白了
zhihui这边的原理图没有接线柱 不是很好懂
