### ISSUE TITLE
是否含有烙铁部分

### ISSUE THREAD

**Issue by L1cardo** [peng-zhihui/OpenHeat#21]
看到代码里面有“烙铁头”字样，但是此项目名称又叫“开源智能加热台”，所以请问，这个项目完成后会包含烙铁部分吗？如果是的话就太好了。
如果不包含烙铁，那我就先自己diy一个了，现在比较纠结😅。

**Comment by song-hailong** [comment]
这个代码，原版就是一个T12烙铁项目[skyblue OpenT12](https://gitee.com/createskyblue/OpenT12)

**Comment by L1cardo** [comment]
> 这个代码，原版就是一个T12烙铁项目[skyblue OpenT12](https://gitee.com/createskyblue/OpenT12)

这个我是了解的，我就想知道稚晖君这个项目完成后是否会包含烙铁，还是说只是加热台。
