### ISSUE TITLE
请问下必须插TYPEC才能开机吗？

### ISSUE THREAD

**Issue by dgsx61** [peng-zhihui/OpenHeat#26]
我这边连接12V/24V供电后，必须插一下TYPEC才能启动

**Comment by dgsx61** [comment]
启动后拔掉typec保持开机。

**Comment by dgsx61** [comment]
启动后拔掉typec，会保持一段时间开机状态，然后假死，不能操作，再插上typec又继续工作，注意是继续不是重新开机。

**Comment by Cardistalive** [comment]
> 我这边连接12V/24V供电后，必须插一下TYPEC才能启动

24V电源哪里购买哒，有没有链接给个

**Comment by dgsx61** [comment]
> > 我这边连接12V/24V供电后，必须插一下TYPEC才能启动
> 
> 24V电源哪里购买哒，有没有链接给个

淘宝24V开关电源 直接买就行了 又不是什么高科技东西

**Comment by dgsx61** [comment]
解决办法：更改VBUS和5V的防倒流二极管位置，确保串口芯片能启动。

**Comment by Cardistalive** [comment]
> > > 我这边连接12V/24V供电后，必须插一下TYPEC才能启动
> > 
> > 
> > 24V电源哪里购买哒，有没有链接给个
> 
> 淘宝24V开关电源 直接买就行了 又不是什么高科技东西

好的，谢谢
