### ISSUE TITLE
software

### ISSUE THREAD

**Issue by litter-hui** [peng-zhihui/OpenHeat#4]
我发现大佬之前说会把创作平台转移到ESP32上。现在真的真把这坑填上了。我本人也是电子爱好者，您能介绍一下您的软件平台吗，我在您之前那个esp32_pico的项目中编程过程中遇到一些问题，我用的是VScode+platformIO插件，希望以后您能多介绍一点软件方面的知识

**Comment by peng-zhihui** [comment]
网上很多教程了，学一下platformIO一劳永逸
